import { rejectAfterOneSecond } from "./baiA03"

async function handleError() {
    try {
        const result = await rejectAfterOneSecond()
        console.log(result)
    } catch (error) {
        console.log("Lá»—i async/await: ", error)
    }
}

handleError()